export const ERROR = 'ERROR';
export const UNSET_ERROR = 'UNSET_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const GET_CURRENT_USER_BOOKMARKS = 'GET_CURRENT_USER_BOOKMARKS';

export const SIGN_UP_COMPLETED = 'SIGN_UP_COMPLETED';

export const GET_TOP_COMPANIES = 'GET_TOP_COMPANIES';
export const GET_NEWS_COMPANIES = 'GET_NEWS_COMPANIES';

export const GET_AVG_PRICES = 'GET_AVG_PRICES';
export const GET_AVG_PRICES_BY_MONTHS = 'GET_AVG_PRICES_BY_MONTHS';

export const END_LOADING = 'END_LOADING';
export const START_LOADING = 'START_LOADING';

export const SET_BOOKMARKS = 'SET_BOOKMARKS';
export const UPDATE_BOOKMARKS_START = 'UPDATE_BOOKMARKS_START';
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';

export const SET_COMPANY = 'SET_COMPANY';
export const SET_COMPANIES_LIST = 'SET_COMPANIES_LIST';
export const SET_COMPANIES_TOTAL = 'SET_COMPANIES_TOTAL';
export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER';
export const PASSWORD_RESET_SEND_TOKEN = 'PASSWORD_RESET_SEND_TOKEN';
export const PASSWORD_RESET_SET_RESET_TOKEN = 'PASSWORD_RESET_SET_RESET_TOKEN';
export const PASSWORD_RESET_REMOVE = 'PASSWORD_RESET_REMOVE ';

export const GET_NEWS = 'GET_NEWS';
